### ISSUE TITLE
Correción en layout.md

### ISSUE THREAD

**Issue by Twinber** [flutter-es/website#26]
En lugar de "Gesticulaciones" que parece referirse a gestos hecho con la cara, pongamos Gestos o en el peor de los casos no traducirlo y dejar Gestures

**Comment by alexcotte** [comment]
Ese cambio no es parte del archivo layout.
es parte del es_ES/_includes/sidebar.html, @Arkangel12 podrías hacer la corrección 🤓

**Comment by alexcotte** [comment]
Les dejo el PR #27
