### ISSUE TITLE
Issue desde la página JSON y serialización

### ISSUE THREAD

**Issue by legallyfree** [flutter-es/website#357]
From URL: https://flutter.io/json/
/// Todas las clases json_serializable deben tener el serializer mixin.
/// Esto hace que sea usable el método toJson() para la clase.
/// Los nombres de los mixin siguen al de la clase fuente, en este caso, User.
```
class User extends Object with _$UserSerializerMixin {
  User(this.name, this.email);
```

estuve haciendo una clase model y la parte de extends Object with _$UserSerializerMixin
ya no me acepta o reconoce, se creo el archivo correspondiente pero esto de extend Object _$UserSerializerMixin no me reconoce, esta des-actualizado la documentación o el problema fue mio?

**Comment by Twinber** [comment]
Lo revisaremos . Gracias por el aviso.

**Comment by Twinber** [comment]
Efectivamente el paquete json_serializable no usa ya ese mixin como se puede ver comparando la doc de la version 0.5.4 (la usada en la doc) con la versión actual (2.0)
https://pub.dartlang.org/documentation/json_serializable/0.5.4/
https://pub.dartlang.org/documentation/json_serializable/latest/

Lo reportaremos a flutter.io para que apliquen la correción.

**Comment by Twinber** [comment]
Lo han corregido pero no en la rama master.
Nosotros nos adelanteremos y lo añadiremos a nuestra traducción
https://github.com/flutter/website/pull/1531/files
