### ISSUE TITLE
El consumo se ha multiplicado x4 desde el cambio de look

### ISSUE THREAD

**Issue by Twinber** [flutter-es/website#512]
https://github.com/flutter/website/issues/2534

**Comment by Twinber** [comment]
No se corresponde con una subida de visitas proporcional
![excesodeconsumo](https://user-images.githubusercontent.com/5513621/54526035-d1b7dd80-4975-11e9-87e2-73a9d36b8393.jpg)

**Comment by NicolasERT** [comment]
Ya está solucionado no?
