### ISSUE TITLE
/get-started/codelab#paso-3-agregar-un-stateful-widget

### ISSUE THREAD

**Issue by luchrv** [flutter-es/website#513]
En su 4to. paso dice: 

> Elmina el código de generación de palabras de MyApp:

Faltó la **i** en **Elimina**

Además el código incorporado es el mismo del 3er paso. El correcto es:
https://flutter.dev/docs/get-started/codelab#d2h-006483

Saludos.

**Comment by Twinber** [comment]
He corregido la i que falta, pero no entiendo a que te refieres con lo de que el código es el mismo.
Estoy comparando paso a paso con flutter.dev y no veo que no coincidan.
