### ISSUE TITLE
'Actualizar Flutter' page issue

### ISSUE THREAD

**Issue by lukealvarez** [flutter-es/website#559]
Page URL: https://flutter-es.io/docs/development/tools/sdk/upgrading.html
Page source: https://github.com/flutter-es/website/tree/dash/src_es/docs/development/tools/sdk/upgrading.md

The page title is wrong. Please, replace "Confiura una sola vez" with "Configura una sola vez".

Thanks! :)

**Comment by Arkangel12** [comment]
already fix
