### ISSUE TITLE
'Gestión sencilla del estado de las aplicaciones' page issue

### ISSUE THREAD

**Issue by murdokiler** [flutter-es/website#563]
Page URL: https://flutter-es.io/docs/development/data-and-backend/state-mgmt/simple.html
Page source: https://github.com/flutter-es/website/tree/dash/src_es/docs/development/data-and-backend/state-mgmt/simple.md

Error de traducción en el siguiente párrafo de la sección **ChangeNotifier**:

> En nuestro ejemplo de aplicación de compras, queremos gestionar el estado del carro en un ChangeNotifier. Creamos una nueva clase que extiende lo extiende como esta:

También al final de la página en la sección **Uniendo todo** la palabra "covierto":

> Puedes revisar el ejemplo covierto en este artículo. Si quieres algo más simple, puedes ver como la sencilla app Counter se ve cuando se construye con provider.

**Comment by Arkangel12** [comment]
closed
