### ISSUE TITLE
'Dentro de Flutter' page issue

### ISSUE THREAD

**Issue by omarSuarezRodriguez** [flutter-es/website#571]
Page URL: https://flutter-es.io/docs/resources/inside-flutter.html
Page source: https://github.com/flutter-es/website/tree/dash/src_es/docs/resources/inside-flutter.md

Buenas tardes señores de Flutter, tengan un cordial saludo

Primeramente felicitarlos por su grandioso trabajo con este excelente Framework, lo mejor que he probado en cuanto a desarrollo y programación confiere,

Les escribo con objeto de comunicar algunos incidentes respecto a la traducción de la página de "Dentro de Flutter", en la cual se pueden observar algunos errores ortográficos, sintácticos o gramaticales

Mi propuesta es que, si ustedes me lo permiten, podría servir como revisor y/o corrector de algunas publicaciones y escritos de la página, mi lengua nativa es el Español, idioma que domino con firmeza, nativo de Cúcuta, Colombia.

Muchas gracias por leerme, si están interesados, estaría encantado de ayudar, mi correo de contacto es:
omar.suarez.rod@gmail.com

Saludos, buen día!

Omar Suarez

**Comment by Arkangel12** [comment]
Hola Omar, muy amable y por supuesto, por favor por aquí mismo responde si aun esta interesado para poder agregarte al equipo de trabajo.

Saludos!
