### ISSUE TITLE
'Perfiles de Rendimiento en Flutter' page issue

### ISSUE THREAD

**Issue by rickymuvel** [flutter-es/website#574]
Page URL: https://flutter-es.io/docs/testing/ui-performance/
Page source: https://github.com/flutter-es/website/tree/dash/src_es/docs/testing/ui-performance/index.md

<img width="886" alt="Captura de Pantalla 2020-04-20 a la(s) 21 00 54" src="https://user-images.githubusercontent.com/1307835/79816978-07ce4a80-834a-11ea-95af-d8d9820874dc.png">

Imagen rota.

**Comment by juanmorillios** [comment]
Gracias, solucionado: issue #574
