### ISSUE TITLE
'Tratar con restricciones de cajas' page issue

### ISSUE THREAD

**Issue by cbritez** [flutter-es/website#582]
Page URL: https://flutter-es.io/docs/development/ui/layout/box-constraints.html
Page source: https://github.com/flutter-es/website/tree/dash/src_es/docs/development/ui/layout/box-constraints.md

En Flutter, los widgets son dibujados por su objeto RenderBox subyacente. Las cajas de renderizado boxes toman las restricciones dadas por sus padres, y se **dimensioan** a si mismos con estas restricciones. Las restricciones consisten en anchos y altos **míbimos** y máximos; las dimensiones consisten en un **acho** y alto específicos.

dimensionan
mínimos 
ancho

**Comment by Arkangel12** [comment]
corregido!
