### ISSUE TITLE
'Cookbook' page issue

### ISSUE THREAD

**Issue by PedroHincapie** [flutter-es/website#585]
Page URL: https://flutter-es.io/docs/cookbook/
Page source: https://github.com/flutter-es/website/tree/dash/src_es/docs/cookbook/index.md

Este cookbook contiene recetas que muestran como resolver problemas comunes cuando escribimos apps Flutter. "Cara" receta esta auto-contenida y puede ser usada como una refrencia para ayudar a construir una aplicación.

Nota: La palabra Cara debe ser reemplazada por Cada

**Comment by xfxstudios** [comment]
En proceso con https://github.com/flutter-es/website/pull/586
