### ISSUE TITLE
'Tratar con restricciones de cajas' page issue

### ISSUE THREAD

**Issue by Saito25** [flutter-es/website#591]
Page URL: https://flutter-es.io/docs/development/ui/layout/box-constraints.html
Page source: https://github.com/flutter-es/website/tree/dash/src_es/docs/development/ui/layout/box-constraints.md

Buenas, no hablo inglés, por lo que redacto el mensaje en español. Espero que puedan entenderme.

En el primer párrafo de la página, dice esto:

"En Flutter, los widgets son dibujados por su objeto RenderBox subyacente. Las cajas de renderizado boxes toman las restricciones dadas por sus padres, y se dimensioan a si mismos con estas restricciones. Las restricciones consisten en anchos y altos **míbimos** y máximos; las dimensiones consisten en un acho y alto específicos."

Esa palabra está mal escrita, debería ser **mínimos**.

Saludos.

**Comment by juanmorillios** [comment]
Gracias @Saíto25 : Solucionado: Tratar con restricciones de cajas' page issue #591
