### ISSUE TITLE
'Actualizar Flutter' page issue

### ISSUE THREAD

**Issue by rimedar** [flutter-es/website#593]
Page URL: https://flutter-es.io/docs/development/tools/sdk/upgrading.html
Page source: https://github.com/flutter-es/website/tree/dash/src_es/docs/development/tools/sdk/upgrading.md

Hola, es solo para informar que hay un error de escritura, el título dice Confiura una sola vez, falta la g.

**Comment by juanmorillios** [comment]
Gracias @rimedar Solucionado:  Configura una sola vez.
